on:
  push:
    branches-ignore:
      - master

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        working-directory: ./frontend
        uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10.16.0"
          registry-url: https://npm.pkg.github.com/
      - name: "Install dependencies"
        working-directory: ./frontend
        run: yarn install --verbose
      - name: "Unit tests"
        working-directory: ./frontend
        run: CI=true yarn test