on:
  push:
    branches-ignore:
      - master
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: "10.16.0"
          registry-url: https://npm.pkg.github.com/
      - name: "Install dependencies"
        working-directory: ${{env.working-directory}}
        run: yarn install --verbose
      - name: "Run unit tests"
        working-directory: ${{env.working-directory}}
        run: CI=true yarn test
